os: linux
dist: xenial

services:
  - docker

archlinux:
  repos:
    - archlinuxfr=http://repo.archlinux.fr/$arch
  packages:
    - python
    - git
  before_install:
    - sudo pacman -Syy
  script:
    - ./install --only yay
    - ./install --except yay
    - ./install -c opt.conf.yaml
    - ./install -c spotify.conf.yaml

language: python
python:
  - "3.9"

script:
  - "curl -s https://raw.githubusercontent.com/mikkeloscar/arch-travis/master/arch-travis.sh | bash"
