os: linux

services:
  - docker

archlinux:
  repos:
    - archlinuxfr=http://repo.archlinux.fr/$arch
  packages:
    - python
    - git
  before_script:
    - sudo pacman -Syy
    - mkdir -p ~/dotfiles-target
    - yay --needed --noconfirm -S zsh ttf-unifont pulseaudio-bluetooth pavucontrol-qt
  script:
    - HOME=~/dotfiles-target ./install


language: python
python:
  - "3.9"
  - "nightly"

sudo: false

script:
  - "curl -s https://raw.githubusercontent.com/mikkeloscar/arch-travis/master/arch-travis.sh | bash"
