os: linux

services:
  - docker

archlinux:
  repos:
    - archlinuxfr=http://repo.archlinux.fr/$arch
  packages:
    - python
    - git
  before_install:
    - pacman -Syy
  script:
    - HOME=~/dotfiles-target ./install


language: python
python:
  - "3.9"
  - "nightly"

sudo: false

before_script:
  - mkdir -p ~/dotfiles-target

script:
  - "curl -s https://raw.githubusercontent.com/mikkeloscar/arch-travis/master/arch-travis.sh | bash"
